<?php
$t = array(
  // Header / Navigation
  'home' => 'Home',
  'documentation' => 'Documentation',
  'construction' => 'Construction',
  'cleaning' => 'Cleaning',
  'digital_services' => 'Digital Services',
  'about_us' => 'About Us',
  'contact' => 'Contact',
  'get_quote' => 'Get a Quote',
  
  // Footer
  'footer_desc' => 'Your integrated partner for premier documentation, construction, and cleaning services.',
  'quick_links' => 'Quick Links',
  'contact_info' => 'Contact Info',
  'address' => 'building 1361 road 1224 block 1012 Al hamalah, Kingdom of Bahrain',
  'rights_reserved' => 'Silver Palace. All Rights Reserved.',

  // Generic
  'learn_more' => 'Learn More',
  'contact_us_today' => 'Contact Us Today',

  // Index (Hero)
  'hero_integrated' => 'Integrated Services Group',
  'hero_title' => 'Complete Documentation, Construction & Cleaning Solutions Under One Roof',
  'hero_subtext' => 'Fast. Trusted. Professional.',
  'our_services' => 'Our Services',

  // Index (Core Services)
  'core_services' => 'Our Core Services',
  'core_services_sub' => 'We provide a comprehensive range of professional services tailored to your needs.',
  
  'doc_services' => 'Documentation Services',
  'doc_f1' => 'CPR',
  'doc_f2' => 'CR Registration',
  'doc_f3' => 'License Services',
  'doc_f4' => 'Visit Visa',
  'doc_f5' => 'Company Visa',
  'doc_f6' => 'Ticket Booking',

  'const_services' => 'Construction Services',
  'const_f1' => 'Villa Construction',
  'const_f2' => 'Building Construction',
  'const_f3' => 'House Maintenance',
  'const_f4' => 'Painting',
  'const_f5' => 'Plumbing',
  'const_f6' => 'Electrical Work',

  'clean_services' => 'Cleaning Services',
  'clean_f1' => 'House Cleaning',
  'clean_f2' => 'Flats Cleaning',
  'clean_f3' => 'Building Cleaning',
  'clean_f4' => 'Office Cleaning',
  'clean_f5' => 'Shops Cleaning',
  'clean_f6' => 'Monthly / Contract / Hourly Base',

  'dig_services' => 'Digital Services',
  'dig_f1' => 'Web Development',
  'dig_f2' => 'E-Commerce & Shopify',
  'dig_f3' => 'Social Media Handling',
  'dig_f4' => 'SEO Optimization',
  'dig_f5' => 'Content Creation',
  'dig_f6' => 'Digital Marketing',

  // Index (Why Choose Us)
  'why_choose_us' => 'Why Choose Silver Palace',
  'why_sub' => 'We are committed to delivering excellence across all our service domains, ensuring your absolute satisfaction.',
  'why_1_title' => 'Fast Processing',
  'why_1_desc' => 'Quick turnaround times for all documentation and applications.',
  'why_2_title' => 'Government Approved Assistance',
  'why_2_desc' => 'Fully compliant and authorized service handling for all visas.',
  'why_3_title' => 'Experienced Construction Team',
  'why_3_desc' => 'Expert engineers and craftsmen building your vision reliably.',
  'why_4_title' => 'Affordable Cleaning Packages',
  'why_4_desc' => 'Flexible cleaning solutions tailored to your specific budget.',
  'why_5_title' => 'Transparent Pricing',
  'why_5_desc' => 'No hidden costs, straightforward and highly competitive rates.',

  // Index (Process)
  'process_title' => 'Our Work Process',
  'process_sub' => 'A streamlined, stress-free approach designed entirely for your convenience.',
  'proc_1_title' => 'Contact Us',
  'proc_1_desc' => 'Reach out with your requirements.',
  'proc_2_title' => 'Free Consultation',
  'proc_2_desc' => 'Discuss details and get expert advice.',
  'proc_3_title' => 'Documentation / Site Visit',
  'proc_3_desc' => 'We review papers or inspect the location.',
  'proc_4_title' => 'Execution',
  'proc_4_desc' => 'Our team gets the job done efficiently.',
  'proc_5_title' => 'Final Delivery',
  'proc_5_desc' => 'Project handover and guaranteed satisfaction.',

  // Index (Testimonials & CTA)
  'testimonials_title' => 'What Our Clients Say',
  'testimonials_sub' => 'Trusted widely by individuals, families, and businesses alike.',
  'test_1' => '"Silver Palace handled our company visa approvals incredibly fast. Their documentation team is very professional and saved us a massive amount of time."',
  'test_1_name' => 'Ahmed Al-Sayed',
  'test_1_role' => 'Business Owner',
  'test_2' => '"We rely on them for monthly office cleaning. The staff is punctual, trustworthy, and leaves the place perfectly spotless every single time."',
  'test_2_name' => 'Sarah Jenkins',
  'test_2_role' => 'Operations Manager',
  'test_3' => '"Outstanding construction services! They maintained our villa\'s plumbing and electrical systems with great expertise. Highly transparent pricing."',
  'test_3_name' => 'Mohammed K.',
  'test_3_role' => 'Homeowner',
  
  'cta_title' => 'Need urgent visa or maintenance service?',
  'cta_sub' => 'Our experts are ready to assist you right now. Get your free consultation.',

  // About
  'about_title' => 'About Silver Palace',
  'about_sub' => 'Your Complete Service Partner for Documentation, Construction & Cleaning Solutions',
  'about_who' => 'Company Overview',
  'about_who_title' => 'Who We Are',
  'about_who_desc1' => 'Silver Palace is a professional service company providing reliable documentation assistance, construction solutions, and cleaning services under one roof.',
  'about_who_desc2' => 'We are committed to delivering fast, transparent, and high-quality services to individuals, families, and businesses. Whether you need help with legal documentation, building construction, property maintenance, or professional cleaning services — we are here to support you with expertise and dedication.',
  'about_trusted' => 'Trusted<br>Partner',
  'about_mission' => 'Our Mission',
  'about_mission_sub' => 'Our mission is simple:',
  'about_mission_quote' => '"To provide trustworthy, affordable, and professional services that make life easier for our clients."',
  'about_mission_desc' => 'We aim to build long-term relationships based on trust, quality, and customer satisfaction.',
  'about_vision' => 'Our Vision',
  'about_vision_desc' => 'To become a leading service provider known for reliability, professionalism, and excellence in documentation, construction, and facility services.',
  'about_core_sub' => 'Dedicated business and residential solutions executed flawlessly.',
  'about_doc_sum' => 'We ensure fast processing and complete guidance from start to finish.',
  'about_const_sum' => 'Our experienced team ensures quality workmanship and timely project completion.',
  'about_clean_sum' => 'We provide professional cleaning with trained staff and modern equipment.',
  'about_why' => 'Why Choose Silver Palace?',
  'about_why1' => 'Professional & Experienced Team',
  'about_why2' => 'Transparent Pricing',
  'about_why3' => 'On-Time Service Delivery',
  'about_why4' => 'Customer Satisfaction Focused',
  'about_why5' => 'Affordable Packages',
  'about_why6' => 'Reliable Support',
  'about_quote' => 'At Silver Palace, we don’t just provide services — we deliver solutions you can trust.',

  // Documentation
  'doc_page_title' => 'Documentation Services',
  'doc_page_sub' => 'Fast processing for visas, licenses, and company registrations.',
  'doc_nav_badge' => 'Expert Assistance',
  'doc_nav_title' => 'Navigating Documentation with Ease',
  'doc_nav_desc1' => 'Silver Palace offers a seamless, hassle-free approach to legal and commercial documentation. Our expert consultants handle all the heavy lifting, dealing directly with government entities and typing centers to ensure your paperwork is processed accurately and promptly.',
  'doc_nav_desc2' => 'Whether you need a new commercial registration, visa renewals for your growing team, or simply want to fly in your family, our dedicated desk ensures that every stamp, signature, and submission is handled efficiently.',
  'doc_what_title' => 'What We Handle',
  'doc_what_sub' => 'Comprehensive corporate and individual processing solutions.',
  
  'doc_s1_title' => 'CPR Registration Assistance',
  'doc_s1_desc' => 'Complete assistance formatting documentation required to issue or renew CPRs for all residents quickly.',
  'doc_s2_title' => 'Commercial Registration (CR)',
  'doc_s2_desc' => 'We handle the end-to-end CR formation process, including amendments, activity additions, and renewals.',
  'doc_s3_title' => 'Business License Processing',
  'doc_s3_desc' => 'Prompt acquisition of specialized governmental and municipal licenses needed for your operations.',
  'doc_s4_title' => 'Visit Visa Processing',
  'doc_s4_desc' => 'Hassle-free application management for family, tourist, and business visit visas with high success rates.',
  'doc_s5_title' => 'Company Visa Services',
  'doc_s5_desc' => 'Managing work permits, labor visas, dependent visas, and residency renewals for corporate staff.',
  'doc_s6_title' => 'Air Ticket Booking',
  'doc_s6_desc' => 'End-to-end travel itinerary planning and immediate ticket booking for international flights.',
  
  'doc_req_title' => 'Standard Required Documents',
  'doc_req_desc' => 'While requirements vary depending on the specific service and nationality, ensuring you have these baseline documents will drastically speed up your processing time.',
  'doc_req_btn' => 'Consult Our Experts',
  
  'doc_r1_title' => 'Passport Copies',
  'doc_r1_desc' => 'High-resolution scans with at least 6 months of validity.',
  'doc_r2_title' => 'Sponsor ID / CR Copy',
  'doc_r2_desc' => 'Clear copy of local sponsor ID or Company CR documentation.',
  'doc_r3_title' => 'Passport Size Photographs',
  'doc_r3_desc' => 'Recent photos with white background (standard size).',
  'doc_r4_title' => 'Educational/Marriage Certificates',
  'doc_r4_desc' => 'Attested copies depending on visa type (dependent/professional).',
  
  'doc_time_title' => 'Estimated Processing Times',
  'doc_time_sub' => 'Transparent timelines so you know exactly when to expect results.',
  
  'doc_t1_badge' => '1 - 2 Days',
  'doc_t1_title' => 'Air Ticket Booking',
  'doc_t1_desc' => 'Immediate booking and confirmation.',
  'doc_t2_badge' => '3 - 5 Days',
  'doc_t2_title' => 'Visit Visas & CPR Renewals',
  'doc_t2_desc' => 'Standard processing depending on nationality.',
  'doc_t3_badge' => '1 - 2 Weeks',
  'doc_t3_title' => 'Company Visas & Permits',
  'doc_t3_desc' => 'Subject to labor market approvals.',
  'doc_t4_badge' => '2 - 4 Weeks',
  'doc_t4_title' => 'New CR & Licensing',
  'doc_t4_desc' => 'Complex activity approvals require varying times.',
  'doc_time_note' => '* Note: Timelines are estimates and subject to government system availability and approval.',

  // Construction
  'const_page_title' => 'Construction Services',
  'const_page_sub' => 'Building your vision with precision, quality, and trust.',
  'const_exp_badge' => '10+ Years',
  'const_exp_text' => 'Experience',
  'const_badge' => 'Premium Quality',
  'const_title' => 'Solid Foundations, Lasting Results',
  'const_desc1' => 'Silver Palace delivers end-to-end construction and maintenance solutions. From laying the first brick of your dream villa to executing complex electrical and plumbing overhauls, our highly skilled engineers and craftsmen are equipped to handle projects of any scale.',
  'const_desc2' => 'We pride ourselves on using premium materials, maintaining stringent safety standards, and keeping absolute transparency in pricing and timelines throughout the development of your project.',
  'const_cap_title' => 'Our Capabilities',
  'const_cap_sub' => 'Comprehensive construction and property maintenance services.',
  
  'const_c1_title' => 'Villa Construction',
  'const_c1_desc' => 'Complete turnkey residential villa projects from initial architectural design to final handover, tailored to your lifestyle requirements.',
  'const_c2_title' => 'Residential Building',
  'const_c2_desc' => 'Multi-story residential apartment construction focusing on structural integrity, modern aesthetics, and building code compliance.',
  'const_c3_title' => 'Maintenance Contracts',
  'const_c3_desc' => 'Comprehensive annual or preventive maintenance contracts (AMC) for buildings, compounds, and commercial properties.',
  'const_c4_title' => 'Plumbing & Electrical',
  'const_c4_desc' => 'Expert troubleshooting, emergency repairs, and complete system installations for water, drainage, and power grids.',
  'const_c5_title' => 'Interior & Exterior Painting',
  'const_c5_desc' => 'Premium surface preparation, weatherproofing, and flawless painting finishes to protect and beautify your property.',
  
  'const_port_title' => 'Portfolio Gallery',
  'const_port_sub' => 'A glimpse into our completed projects and ongoing developments.',
  'const_p1_title' => 'Luxury Villa Development',
  'const_p1_desc' => 'Turnkey Construction',
  'const_p2_title' => 'Commercial Complex',
  'const_p2_desc' => 'Structural Engineering',
  'const_p3_title' => 'Piping Infrastructure',
  'const_p3_desc' => 'Industrial Plumbing',
  'const_p4_title' => 'Residential Interiors',
  'const_p4_desc' => 'Premium Painting',
  'const_p5_title' => 'Main Panel Installation',
  'const_p5_desc' => 'Electrical Engineering',
  'const_p6_title' => 'Apartment Building',
  'const_p6_desc' => 'Exterior Finishing',
  
  'const_proc_title' => 'Our Construction Process',
  'const_proc_sub' => 'A transparent, milestone-driven approach to bringing your project to life.',
  'const_pr1_title' => 'Site Visit',
  'const_pr1_desc' => 'Initial inspection and measurement.',
  'const_pr2_title' => 'Quotation',
  'const_pr2_desc' => 'Detailed breakdown of costs.',
  'const_pr3_title' => 'Agreement',
  'const_pr3_desc' => 'Finalizing contracts and timelines.',
  'const_pr4_title' => 'Construction',
  'const_pr4_desc' => 'Execution per engineering standards.',
  'const_pr5_title' => 'Handover',
  'const_pr5_desc' => 'Final review and project delivery.',
  
  'const_cta_title' => 'Ready to build your dream project?',
  'const_cta_sub' => 'Schedule a site visit with our lead engineers today.',
  'const_cta_btn' => 'Request Site Visit',

  // Cleaning
  'clean_page_title' => 'Cleaning Services',
  'clean_page_sub' => 'Spotless spaces for a healthier, more productive environment.',
  'clean_badge' => 'Trusted Professionals',
  'clean_title' => 'Immaculate Cleaning Solutions',
  'clean_desc1' => 'At Silver Palace, we understand that a clean environment is vital for both health and productivity. Our dedicated cleaning teams use industry-leading techniques and eco-friendly products to deliver a pristine finish every single time.',
  'clean_desc2' => 'Whether you need a quick deep clean for your apartment or a reliable, year-long contract to manage an entire commercial building, we offer highly flexible and customized solutions tailored exactly to your schedule and budget.',
  'clean_eco_badge' => 'Eco-Friendly<br>Products',
  'clean_dom_title' => 'Our Cleaning Domains',
  'clean_dom_sub' => 'Specialized teams for both your living and working spaces.',
  'clean_res_title' => 'Residential Cleaning',
  'clean_res_desc' => 'We treat your home with the utmost care, ensuring a spotless, sanitized living space for you and your family.',
  'clean_res_1' => '<span class="fw-bold">House Cleaning:</span> Comprehensive top-to-bottom dusting and sanitization.',
  'clean_res_2' => '<span class="fw-bold">Flats & Apartments:</span> Fast and efficient cleaning for modern flats.',
  'clean_res_3' => '<span class="fw-bold">Villas:</span> Deep cleaning customized for multi-level, large properties.',
  'clean_com_title' => 'Commercial Cleaning',
  'clean_com_desc' => 'Maintain a professional, hygienic atmosphere that impresses clients and boosts employee morale.',
  'clean_com_1' => '<span class="fw-bold">Offices:</span> Desk sanitization, pantry upkeep, and carpet vacuuming.',
  'clean_com_2' => '<span class="fw-bold">Shops & Retail:</span> Floor polishing, window displays, and customer area deep cleans.',
  'clean_com_3' => '<span class="fw-bold">Entire Buildings:</span> Corridors, lobbies, staircases, and external facade sweeping.',
  'clean_price_title' => 'Flexible Pricing Models',
  'clean_price_sub' => 'Choose the engagement plan that perfectly matches your requirements.',
  'clean_p1_title' => 'Hourly Base',
  'clean_p1_desc' => 'Perfect for one-off deep cleans or post-party/post-construction quick sweeps.',
  'clean_p1_f1' => 'Minimum 4 hours booking',
  'clean_p1_f2' => 'All cleaning equipment provided',
  'clean_p1_f3' => 'Same-day availability (subject to slot)',
  'clean_p1_f4' => 'Highly flexible scheduling',
  'clean_p1_btn' => 'Book a Slot',
  'clean_p2_badge' => 'Most Popular',
  'clean_p2_title' => 'Monthly Contract',
  'clean_p2_desc' => 'Ideal for consistent office upkeep and busy households wanting regular visits.',
  'clean_p2_f1' => 'Dedicated cleaning staff',
  'clean_p2_f2' => 'Fixed days and times per week',
  'clean_p2_f3' => 'Discounted recurring rates',
  'clean_p2_f4' => 'Replacements available on sick leaves',
  'clean_p2_btn' => 'Get Monthly Quote',
  'clean_p3_title' => 'Yearly Contract',
  'clean_p3_desc' => 'The ultimate set-and-forget solution for large buildings, compounds, and corporate centers.',
  'clean_p3_f1' => 'Heavily discounted AMC rates',
  'clean_p3_f2' => 'Dedicated Account Manager',
  'clean_p3_f3' => 'Monthly deep-clean inclusion',
  'clean_p3_f4' => 'Full supply of consumables option',
  'clean_p3_btn' => 'Discuss AMC Setup',
  'clean_cta_title' => 'Need a spotless space?',
  'clean_cta_sub' => 'Contact us now to schedule your first cleaning session.',
  'clean_cta_btn' => 'Schedule Cleaning'
);
?>
